FROM mtgupf/essentia

WORKDIR /app

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
    g++ make cmake \
    libx11-dev libgtk-3-dev libopenblas-dev liblapack-dev \
    libboost-all-dev libeigen3-dev libssl-dev \
    libdlib-dev wget git python3-pip && \
    rm -rf /var/lib/apt/lists/*

# Clone and build dlib
RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && cd build && \
    cmake .. -DDLIB_NO_GUI_SUPPORT=ON && \
    cmake --build . --config Release && \
    make install && \
    ldconfig && \
    cd ../..

# Clone and build Shark
RUN git clone https://github.com/Shark-ML/Shark.git && \
    cd Shark && \
    mkdir build && cd build && \
    cmake .. && \
    make -j"$(nproc)" && \
    make install && ldconfig && \
    cd ../..

# Clone and build Cereal
RUN git clone https://github.com/USCiLab/cereal.git && \
    cd cereal && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j"$(nproc)" && \
    make install && \
    cd ../..

# Install additional dependencies for mlpack
RUN apt-get update && \
    apt-get install -y --no-install-recommends libensmallen-dev libomp-dev && \
    rm -rf /var/lib/apt/lists/*

# Download and install Armadillo
RUN wget https://sourceforge.net/projects/arma/files/armadillo-11.4.4.tar.xz && \
    tar -xvf armadillo-11.4.4.tar.xz && \
    cd armadillo-11.4.4 && \
    cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j"$(nproc)" && \
    make install && \
    cd .. && \
    rm -rf armadillo-11.4.4*

# Clone and build mlpack
RUN git clone https://github.com/mlpack/mlpack.git && \
    cd mlpack && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local \
             -DBUILD_PYTHON_BINDINGS=OFF \
             -DBUILD_TESTS=OFF && \
    make -j5 && \
    make install && \
    ldconfig && \
    cd ../.. && \
    rm -rf mlpack

COPY .. /app/
