FROM mtgupf/essentia

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
    g++ make cmake \
    libx11-dev libgtk-3-dev libopenblas-dev liblapack-dev \
    libboost-all-dev libeigen3-dev libssl-dev \
    libdlib-dev \
    wget git python3-pip

RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && cd build && \
    cmake .. -DDLIB_NO_GUI_SUPPORT=ON && \
    cmake --build . --config Release && \
    make install && \
    ldconfig && \
    cd ../..

RUN git clone https://github.com/Shark-ML/Shark.git && \
    cd Shark && \
    mkdir build && cd build && \
    cmake .. && \
    make -j"$(nproc)" && \
    make install && ldconfig && \
    cd ../..

    
    # Install mlpack from the distro in a final layer (minimal rebuild)
RUN apt-get update && \
    apt-get install -y --no-install-recommends libensmallen-dev libomp-dev \
    g++ make cmake \
    libx11-dev libgtk-3-dev libopenblas-dev liblapack-dev \
    libboost-all-dev libeigen3-dev libssl-dev \
    libdlib-dev libcereal-dev \
    wget git python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://sourceforge.net/projects/arma/files/armadillo-11.4.4.tar.xz && \
    tar -xvf armadillo-11.4.4.tar.xz && \
    cd armadillo-11.4.4 && \
    cmake . -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j"$(nproc)" && \
    make install && \
    cd .. && \
    rm -rf armadillo-11.4.4*

RUN git clone https://github.com/mlpack/mlpack.git && \
    cd mlpack && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local \
             -DBUILD_PYTHON_BINDINGS=OFF \
             -DBUILD_TESTS=OFF && \
    make -j"$(nproc)" && \
    make install && \
    ldconfig && \
    cd ../.. && \
    rm -rf mlpack

COPY .. /app/