services:
  audio_classification:
    build:
      context: ..
      dockerfile: ./deploy/dockerfile
    volumes:
      - ../audio:/app/audio
      - ../data/output:/app/data/output
      - ../data/datasets:/app/data/datasets
    working_dir: /app