FROM mtgupf/essentia

WORKDIR /app

RUN apt-get update && \
    apt-get install -y g++ make cmake \
    libx11-dev libgtk-3-dev libopenblas-dev liblapack-dev \
    wget git python3-pip

RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && cd build && \
    cmake .. -DDLIB_NO_GUI_SUPPORT=ON && \
    cmake --build . --config Release && \
    make install && \
    ldconfig

COPY .. /app/

RUN g++ core/feature_extractors/mfcc.cpp core/main.cpp -o main \
    -I/usr/local/include/essentia/ \
    -I/usr/local/include \
    -L/usr/local/lib \
    -lessentia -ldlib -Iinclude


CMD ["./main"]